# Generated by Django 2.2.6 on 2020-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='обо мне', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_auths',
            field=models.CharField(default='Буковски', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.CharField(default='Фактотум', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Имя', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=50),
        ),
    ]
