# Generated by Django 2.2.6 on 2020-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0002_auto_20200117_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_quote',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
